server:
  port: 8761 # Default Eureka server port

spring:
  application:
    name: service-registry

  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
  config:
    import: "optional:configserver:"

eureka:
  client:
    # no need to register itself to registry
#    registerWithEureka: false
#    fetchRegistry: false
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false # For development, can be true in production
    # https://www.baeldung.com/eureka-self-preservation-renewal
    myUrl: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

